//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Descricao { get; set; }
        public int IDStatus { get; set; }
        public int IDUsuario { get; set; }
    
        public virtual StatusTarefa StatusTarefa { get; set; }
        public virtual Usuário Usuário { get; set; }
    }
}
